import { Monitor } from "./uptime.interfaces";

export const sampleMonitors: Monitor[] = [
    {
        id: "1",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "2",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "3",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "4",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "5",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "6",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "7",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "8",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "9",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "10",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "11",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "12",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "13",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "14",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "15",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "16",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "17",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "18",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "19",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "20",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "21",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "22",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "23",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "24",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "25",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "26",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "27",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "28",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "29",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "30",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "31",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "32",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "33",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "34",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "35",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "36",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "37",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "38",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "39",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "40",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "41",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "42",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "43",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "44",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "45",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "46",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "47",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "48",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "49",
        monitorType: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "50",
        monitorType: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "51",
        monitorType: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "52",
        monitorType: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "53",
        monitorType: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "54",
        monitorType: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "55",
        monitorType: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "56",
        monitorType: "SSL",
        name: "Inactive Website end?",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
];