import { Monitor } from "./uptime.interfaces";

export const sampleMonitors: Monitor[] = [
    {
        id: "1",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "2",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "3",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "4",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "5",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "6",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "7",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "8",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "9",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "10",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "11",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "12",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "13",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "14",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "15",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "16",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "17",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "18",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "19",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "20",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "21",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "22",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "23",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "24",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "25",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "26",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "27",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "28",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "29",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "30",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "31",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "32",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "33",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "34",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "35",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "36",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "37",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "38",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "39",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "40",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "41",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "42",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "43",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "44",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "45",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "46",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "47",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "48",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "49",
        monitor_type: "SSL",
        name: "Inactive Website",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
    {
        id: "50",
        monitor_type: "Heartbeat",
        name: "Twitter",
        url: "https://twitter.com",
        isUp: true,
        lastChange: "2021-10-19T15:39:31Z",
    },
    {
        id: "51",
        monitor_type: "Ping",
        name: "Google",
        url: "https://www.google.com",
        isUp: false,
        lastChange: "2021-10-19T14:39:31Z",
    },
    {
        id: "52",
        monitor_type: "GET",
        name: "Dev Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "2021-10-19T12:39:31Z",
    },
    {
        id: "53",
        monitor_type: "POST",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com",
        isUp: false,
        lastChange: "2021-09-19T15:39:31Z",
    },
    {
        id: "54",
        monitor_type: "SSL",
        name: "Test Website",
        url: "https://something.com",
        isUp: true,
        lastChange: "202-10-19T1:39:31Z"
    },
    {
        id: "55",
        monitor_type: "SSL",
        name: "A really long name for someone with nothing to think about",
        url: "https://something.com/nothing/anything/test/123xyz",
        isUp: false,
        lastChange: null,
    },
    {
        id: "56",
        monitor_type: "SSL",
        name: "Inactive Website end?",
        url: "https://something.com",
        isUp: false,
        lastChange: null,
    },
];