{
 "title": "Glitchtip SLO",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Glitchtip SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability of HTTP Requests",
   "type": "timeseries",
   "description": "SLI Specification: \nType: Availability\nSpecification: 95% of successful HTTP requests in the past 28 days were successful.\n\nWe measure the ratio of the total number of successful HTTP requests and the total number of HTTP requests regardless of status.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{exported_namespace=~\"glitchtip-(stage|production)\", code!=\"5xx\"}[1d])) by (exported_namespace) / sum(rate(haproxy_backend_connections_total{backend=~\".*https.*\", exported_namespace=~\"glitchtip-(stage|production)\"}[1d])) by (exported_namespace)) * 100"
    }
   ]
  },
  {
   "title": "Latency of HTTP Requests",
   "type": "timeseries",
   "description": "SLI Specification:\nType: Latency\n90% of the HTTP requests in the past 28 days were completed in less than 400 milliseconds.\n\nWe measure The ratio of the number of HTTP requests with latencies less than 400 milliseconds and the total number of HTTP requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"0.5\", job=\"glitchtip-web\"}[28d])) by(job)\n/\nsum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"+Inf\", job=\"glitchtip-web\"}[28d])) by(job)) * 100"
    }
   ]
  },
  { "title": "Error Budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Remaining Availability Error Budget",
   "type": "stat",
   "description": "% of Remaining Error Budget = (Error Budget - Consumed Error Budget) / Error Budget",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - ((sum(increase(haproxy_backend_http_responses_total{exported_namespace=~\"glitchtip-(stage|production)\", code=\"5xx\"}[28d]))) / (0.05 * sum(increase(haproxy_backend_connections_total{backend=~\".*https.*\", exported_namespace=~\"glitchtip-(stage|production)\"}[28d]))))) * 100"
    }
   ]
  },
  {
   "title": "Remaining Latency Error Budget",
   "type": "stat",
   "description": "% of Remaining Error Budget = (Error Budget - Consumed Error Budget) / Error Budget",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (0.1 * (sum(rate(django_http_requests_latency_seconds_by_view_method_count[28d])) by (job))) - (\n        (\n            sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"+Inf\"}[28d])) by (job) - sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"0.5\"}[28d])) by (job)\n        )\n        )) / (0.1 * (sum(rate(django_http_requests_latency_seconds_by_view_method_count[28d])) by (job)))"
    }
   ]
  },
  { "title": "Firing Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (alertname) (changes(ALERTS_FOR_STATE{job=\"glitchtip-web\"}[24h]) OR vector(0))"
    }
   ]
  }
 ]
}