export const orgDetails = {
  id: 96,
  name: "brands",
  slug: "brands",
  dateCreated: "2021-01-22T18:14:17.104804Z",
  status: { id: "active", name: "active" },
  avatar: { avatarType: "", avatarUuid: null },
  isEarlyAdopter: false,
  require2FA: false,
  isAcceptingEvents: true,
};

export const paginatorPageOne = {
  hits: "6",
  maxHits: "1000",
  page: null,
  nextPageURL:
    "http://localhost:4200/api/0/organizations/brands/projects/?cursor=cD0yMDIxLTAxLTIyKzE4JTNBMjUlM0EyMS40MDI2NzQlMkIwMCUzQTAw&query=is%3Aunresolved",
  loading: false,
  initialLoadComplete: true,
  hasNextPage: true,
  hasPreviousPage: false,
  nextPageParams: {
    cursor: "cD0yMDIxLTAxLTIyKzE4JTNBMjUlM0EyMS40MDI2NzQlMkIwMCUzQTAw",
    query: "is:unresolved",
  },
  previousPageParams: null,
  count: "6",
};

export const projectsPageOne = [
  {
    avatar: { avatarType: "", avatarUuid: null },
    color: "",
    features: [],
    firstEvent: null,
    hasAccess: true,
    id: "117",
    isBookmarked: false,
    isInternal: false,
    isMember: true,
    isPublic: false,
    name: "apple",
    organization: {
      id: 96,
      name: "brands",
      slug: "brands",
      dateCreated: "2021-01-22T18:14:17.104804Z",
      status: { id: "active", name: "active" },
      avatar: { avatarType: "", avatarUuid: null },
      isEarlyAdopter: false,
      require2FA: false,
      isAcceptingEvents: true,
    },
    teams: [{ id: 94, slug: "retail" }],
    scrubIPAddresses: true,
    slug: "apple",
    dateCreated: "2021-01-22T18:26:07.305805Z",
    platform: "",
  },
  {
    avatar: { avatarType: "", avatarUuid: null },
    color: "",
    features: [],
    firstEvent: null,
    hasAccess: true,
    id: "116",
    isBookmarked: false,
    isInternal: false,
    isMember: true,
    isPublic: false,
    name: "target",
    organization: {
      id: 96,
      name: "brands",
      slug: "brands",
      dateCreated: "2021-01-22T18:14:17.104804Z",
      status: { id: "active", name: "active" },
      avatar: { avatarType: "", avatarUuid: null },
      isEarlyAdopter: false,
      require2FA: false,
      isAcceptingEvents: true,
    },
    teams: [{ id: 94, slug: "retail" }],
    scrubIPAddresses: true,
    slug: "target",
    dateCreated: "2021-01-22T18:25:55.720534Z",
    platform: "",
  },
  {
    avatar: { avatarType: "", avatarUuid: null },
    color: "",
    features: [],
    firstEvent: null,
    hasAccess: true,
    id: "115",
    isBookmarked: false,
    isInternal: false,
    isMember: true,
    isPublic: false,
    name: "costco",
    organization: {
      id: 96,
      name: "brands",
      slug: "brands",
      dateCreated: "2021-01-22T18:14:17.104804Z",
      status: { id: "active", name: "active" },
      avatar: { avatarType: "", avatarUuid: null },
      isEarlyAdopter: false,
      require2FA: false,
      isAcceptingEvents: true,
    },
    teams: [{ id: 94, slug: "retail" }],
    scrubIPAddresses: true,
    slug: "costco",
    dateCreated: "2021-01-22T18:25:46.006261Z",
    platform: "",
  },
  {
    avatar: { avatarType: "", avatarUuid: null },
    color: "",
    features: [],
    firstEvent: null,
    hasAccess: true,
    id: "114",
    isBookmarked: false,
    isInternal: false,
    isMember: true,
    isPublic: false,
    name: "kroger",
    organization: {
      id: 96,
      name: "brands",
      slug: "brands",
      dateCreated: "2021-01-22T18:14:17.104804Z",
      status: { id: "active", name: "active" },
      avatar: { avatarType: "", avatarUuid: null },
      isEarlyAdopter: false,
      require2FA: false,
      isAcceptingEvents: true,
    },
    teams: [{ id: 94, slug: "retail" }],
    scrubIPAddresses: true,
    slug: "kroger",
    dateCreated: "2021-01-22T18:25:33.100369Z",
    platform: "",
  },
  {
    avatar: { avatarType: "", avatarUuid: null },
    color: "",
    features: [],
    firstEvent: null,
    hasAccess: true,
    id: "113",
    isBookmarked: false,
    isInternal: false,
    isMember: true,
    isPublic: false,
    name: "amazon",
    organization: {
      id: 96,
      name: "brands",
      slug: "brands",
      dateCreated: "2021-01-22T18:14:17.104804Z",
      status: { id: "active", name: "active" },
      avatar: { avatarType: "", avatarUuid: null },
      isEarlyAdopter: false,
      require2FA: false,
      isAcceptingEvents: true,
    },
    teams: [{ id: 94, slug: "retail" }],
    scrubIPAddresses: true,
    slug: "amazon",
    dateCreated: "2021-01-22T18:25:21.402674Z",
    platform: "",
  },
];
